### ISSUE TITLE
Integrate csmith with Travis

### ISSUE THREAD

**Issue by yulvil** [elliotchance/c2go#333]
First step is to have c2go work with all the options disabled. Then we can integrate csmith with travis and slowly enable options as the functionalities are implemented.

http://embed.cs.utah.edu/csmith/

```
csmith -o main.c \
--no-argc \
--no-arrays \
--no-bitfields \
--no-checksum \
--no-comma-operators \
--no-compound-assignment \
--no-consts \
--divs \
--no-embedded-assigns \
--no-pre-incr-operator \
--no-pre-decr-operator \
--no-post-incr-operator \
--no-post-decr-operator \
--no-unary-plus-operator \
--no-jumps \
--longlong \
--float \
--main \
--math64 \
--no-inline-function \
--max-array-dim 1 \
--max-pointer-depth 1 \
--no-safe-math \
--no-packed-struct \
--no-unions \
--no-volatiles \
--no-volatile-pointers \
--no-const-pointers \
--no-builtins \
--max-nested-struct-level 0 \
--no-dangling-global-pointers \
--no-return-dead-pointer \
--max-struct-nested-level 1 \
--strict-float \
--no-int8 \
--no-uint8
```

**Comment by elliotchance** [comment]
1. Is this the complete list of options?
2. Does this mean that some like `--math64` are actually enabled?
3. Does it currently generate C code that passes in c2go?

**Comment by Konstantin8105** [comment]
:+1 nice tool

**Comment by Konstantin8105** [comment]
May be we will create a some place with "now that tests are fail".
For example, steps:
1) create folder`./tests/fail/`
2) add tests *.c in folder "fail".
3) add go Tests with checking - "Ok in gcc, Fail in transpile" without panics.

**Comment by Konstantin8105** [comment]
In my [project](https://github.com/Konstantin8105/c2go-rating) added `csmith` and generates C files. Typically problem is `panic` like that:
```
panic: invalid identity: 'U0 *SliceToU0Slice' [recovered]
	panic: bad type: 'noarch.U0 *SliceToU0Slice'

goroutine 1 [running]:
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc421233200, 0x19)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x5a1480, 0xc421234da0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/elliotchance/c2go/util.NewIdent(0xc421233207, 0x12, 0x6bc660)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:240 +0x9b5
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc421233200, 0x19, 0xc421233200, 0x19)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:90 +0x359
```
