### ISSUE TITLE
AST panic: FunctionDecl

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#370]
```
panic: could not match regexp with string
^(?P<address>[0-9a-fx]+) (?:prev (?P<prev>0x[0-9a-f]+) )?<(?P<position1>.*?)>(?P<position2> <scratch space>[^ ]+| [^ ]+)?(?P<implicit> implicit)?(?P<used> used)?(?P<referenced> referenced)? (?P<name>[_\w]+) '(?P<type>.*?)'(:'(?P<type2>.*?)')?(?P<extern> extern)?(?P<static> static)?(?P<inline> inline)?[\s]*$
0x30bdba8 parent 0x304fbb0 <col:3, col:38> col:30 used getinfo 'enum countries ()'


goroutine 38 [running]:
github.com/elliotchance/c2go/ast.groupsFromRegex(0xc4200ee140, 0x134, 0xc420186f66, 0x52, 0xc4201b0a00)
	/home/lepricon/go/src/github.com/elliotchance/c2go/ast/ast.go:250 +0x3a6
github.com/elliotchance/c2go/ast.parseFunctionDecl(0xc420186f66, 0x52, 0x5e1b7c)
	/home/lepricon/go/src/github.com/elliotchance/c2go/ast/function_decl.go:25 +0x62
github.com/elliotchance/c2go/ast.Parse(0xc420186f59, 0x5f, 0x5e038d, 0x5)
	/home/lepricon/go/src/github.com/elliotchance/c2go/ast/ast.go:128 +0x1c18
main.convertLinesToNodes(0xc42018a500, 0xc6, 0xc6, 0x0, 0x0, 0x0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/main.go:96 +0x198
main.convertLinesToNodesParallel.func1.2(0xc420102360, 0xc4200ea378, 0xc42018a500, 0xc6, 0xc6, 0x0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/main.go:128 +0x59
created by main.convertLinesToNodesParallel.func1
	/home/lepricon/go/src/github.com/elliotchance/c2go/main.go:126 +0x1b8
```
```
panic: could not match regexp with string
^(?P<address>[0-9a-fx]+) (?:prev (?P<prev>0x[0-9a-f]+) )?<(?P<position1>.*?)>(?P<position2> <scratch space>[^ ]+| [^ ]+)?(?P<implicit> implicit)?(?P<used> used)?(?P<referenced> referenced)? (?P<name>[_\w]+) '(?P<type>.*?)'(:'(?P<type2>.*?)')?(?P<extern> extern)?(?P<static> static)?(?P<inline> inline)?[\s]*$
0x36d5bd8 parent 0x361cbb0 <col:3, col:22> col:12 used integrand 'double ()'


goroutine 36 [running]:
github.com/elliotchance/c2go/ast.groupsFromRegex(0xc4200baf00, 0x134, 0xc420248a4e, 0x4c, 0xc42020b4e0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/ast/ast.go:250 +0x3a6
github.com/elliotchance/c2go/ast.parseFunctionDecl(0xc420248a4e, 0x4c, 0x5e1b7c)
	/home/lepricon/go/src/github.com/elliotchance/c2go/ast/function_decl.go:25 +0x62
github.com/elliotchance/c2go/ast.Parse(0xc420248a41, 0x59, 0x5e038d, 0x5)
	/home/lepricon/go/src/github.com/elliotchance/c2go/ast/ast.go:128 +0x1c18
main.convertLinesToNodes(0xc420254c50, 0x2ed, 0x2ed, 0x0, 0x0, 0x0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/main.go:96 +0x198
main.convertLinesToNodesParallel.func1.2(0xc420262120, 0xc42025e000, 0xc420254c50, 0x2ed, 0x2ed, 0x0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/main.go:128 +0x59
created by main.convertLinesToNodesParallel.func1
	/home/lepricon/go/src/github.com/elliotchance/c2go/main.go:126 +0x1b8
```

**Comment by Konstantin8105** [comment]
```
panic: could not match regexp with string
^(?P<address>[0-9a-fx]+) (?:prev (?P<prev>0x[0-9a-f]+) )?<(?P<position1>.*?)>(?P<position2> <scratch space>[^ ]+| [^ ]+)?(?P<implicit> implicit)?(?P<used> used)?(?P<referenced> referenced)? (?P<name>[_\w]+) '(?P<type>.*?)'(:'(?P<type2>.*?)')?(?P<extern> extern)?(?P<static> static)?(?P<inline> inline)?[\s]*$
0x206e900 parent 0x2000bb0 <col:2, col:20> col:7 used reverse 'void (char *)'


goroutine 8 [running]:
github.com/elliotchance/c2go/ast.groupsFromRegex(0xc420420f00, 0x134, 0xc4200e4d31, 0x4d, 0x2)
        /home/konstantin/go/src/github.com/elliotchance/c2go/ast/ast.go:250 +0x3cc
```

**Comment by elliotchance** [comment]
Easy fix with a test case?

**Comment by Konstantin8105** [comment]
```
panic: could not match regexp with string
^(?P<address>[0-9a-fx]+) (?:prev (?P<prev>0x[0-9a-f]+) )?<(?P<position1>.*?)>(?P<position2> <scratch space>[^ ]+| [^ ]+)?(?P<implicit> implicit)?(?P<used> used)?(?P<referenced> referenced)? (?P<name>[_\w]+) '(?P<type>.*?)'(:'(?P<type2>.*?)')?(?P<extern> extern)?(?P<static> static)?(?P<inline> inline)?[\s]*$
0x353d3b8 parent 0x31e9ba0 prev 0x33b0810 <col:2, col:30> col:22 used dmatrix 'double **(long, long, long, long)'


goroutine 37 [running]:
github.com/elliotchance/c2go/ast.groupsFromRegex(0xc4209dd2c0, 0x134, 0xc421783178, 0x71, 0xc421783178)
	/home/konstantin/go/src/github.com/elliotchance/c2go/ast/ast.go:250 +0x3cc
github.com/elliotchance/c2go/ast.parseFunctionDecl(0xc421783178, 0x71, 0x5ea7b5)
	/home/konstantin/go/src/github.com/elliotchance/c2go/ast/function_decl.go:40 +0x62
github.com/elliotchance/c2go/ast.Parse(0xc42178316b, 0x7e, 0x5e8c75, 0x5)
	/home/konstantin/go/src/github.com/elliotchance/c2go/ast/ast.go:128 +0x2251
main.convertLinesToNodes(0xc42018f360, 0x4913, 0x4913, 0x0, 0x0, 0x0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/main.go:96 +0x196
main.convertLinesToNodesParallel.func1.2(0xc42006c2a0, 0xc42000c008, 0xc42018f360, 0x4913, 0x4913, 0x0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/main.go:128 +0x59
created by main.convertLinesToNodesParallel.func1
	/home/konstantin/go/src/github.com/elliotchance/c2go/main.go:132 +0x1b6

```
