### ISSUE TITLE
Nil problem of Go AST tree

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#375]
Examples:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4cac8a]

goroutine 1 [running]:
go/ast.(*UnaryExpr).End(0xc421274e80, 0x0)
	/usr/local/go/src/go/ast/ast.go:473 +0x2a
go/printer.(*printer).exprList(0xc421210590, 0x0, 0xc4211d01b0, 0x1, 0x1, 0x1, 0x1, 0x0)
	/usr/local/go/src/go/printer/nodes.go:132 +0x14c
go/printer.(*printer).expr1(0xc421210590, 0x6bc260, 0xc4212765c0, 0x0, 0x1)
	/usr/local/go/src/go/printer/nodes.go:816 +0x2386
go/printer.(*printer).expr(0xc421210590, 0x6bc260, 0xc4212765c0)
	/usr/local/go/src/go/printer/nodes.go:922 +0x51
```
```
panic: right is nil

goroutine 1 [running]:
github.com/elliotchance/c2go/util.PanicIfNil(0x0, 0x0, 0x5e1d86, 0xc)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/errors.go:9 +0x77
github.com/elliotchance/c2go/util.NewBinaryExpr(0x6bc660, 0xc4211b7c00, 0x2d, 0x0, 0x0, 0xc420c794af, 0x7, 0x0, 0x6f14c8, 0x0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:185 +0x9b
github.com/elliotchance/c2go/transpiler.transpileBinaryOperator(0xc420aa3e60, 0xc420080000, 0x0, 0x0, 0x6f14c8, 0x0, 0x0, 0x0, 0x6f14c8, 0x0, ...)
	/home/lepricon/go/src/github.com/elliotchance/c2go/transpiler/binary.go:317 +0x1ff0
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x6bd2a0, 0xc420aa3e60, 0xc420080000, 0x0, 0x0, 0x6f14c8, 0x0, 0x0, 0x0, 0x0, ...)
	/home/lepricon/go/src/github.com/elliotchance/c2go/transpiler/transpiler.go:137 +0xf2f
github.com/elliotchance/c2go/transpiler.transpileParenExpr(0xc420aa3dd0, 0xc420080000, 0xc420080000, 0x0, 0x6bc8a0, 0xc4211b7be0, 0xc4211ad590, 0x6, 0x6f14c8, 0x0, ...)
	/home/lepricon/go/src/github.com/elliotchance/c2go/transpiler/operators.go:107 +0xac
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x534fb3]

goroutine 1 [running]:
go/printer.(*printer).exprList(0xc420e77388, 0x0, 0xc4210e6450, 0x1, 0x1, 0x1, 0x1, 0x0)
	/usr/local/go/src/go/printer/nodes.go:131 +0xf3
go/printer.(*printer).expr1(0xc420e77388, 0x6bc260, 0xc4210ea080, 0x0, 0x1)
	/usr/local/go/src/go/printer/nodes.go:816 +0x2386
go/printer.(*printer).expr(0xc420e77388, 0x6bc260, 0xc4210ea080)
	/usr/local/go/src/go/printer/nodes.go:922 +0x51
go/printer.(*printer).printNode(0xc420e77388, 0x5afa40, 0xc4210ea080, 0xc4214077c0, 0x0)
	/usr/local/go/src/go/printer/printer.go:1123 +0x381
```

###Solution
Create a walker of AST GO TREE for found and removing nil.

**Comment by elliotchance** [comment]
I haven't seen the references PR yet (so that may have already solved it) but to get around these issues we have util functions that will panic on when trying to create a Go AST elements with a `nil` input. The panic will show the backtrace.

**Comment by Konstantin8105** [comment]
In that example panic from GO AST package and all panic started from
https://github.com/elliotchance/c2go/blob/991feb4141b2a3d029241ce611a95ac0da55bf52/program/program.go#L223
So, it is mot clear to identify location wil nil.
