### ISSUE TITLE
union pointer panic

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#476]
```c
union U1 {
   int  f0;
   int  f1;
   int  f2;
   volatile int  f3;
   int  f4;
};


static volatile union U1 g_82 = {3UL};

static union U1 g_228[5][6] = {
{{4294967292UL},{4294967295UL},{0UL},{0x034B4D2AL},{0UL},{4294967295UL}},
{{0UL},{4294967292UL},{0x8F8EAD33L},{0x0B072DD7L},{0x0B072DD7L},{0x8F8EAD33L}},
{{0UL},{0UL},{0x0B072DD7L},{0x034B4D2AL},{0x4F7FA5D5L},{0x034B4D2AL}},{{4294967292UL},{0UL},{4294967292UL},{0x8F8EAD33L},{0x0B072DD7L},{0x0B0$
{{4294967295UL},{4294967292UL},{4294967292UL},{4294967295UL},{0UL},{0x034B4D2AL}}
};

static union U1 *g_506 = &g_228[2][4];
static union U1 **g_1246 = &g_506;
static union U1 ***g_1245 = &g_1246; // << --- PROBLEM HERE


int main(){
return 0;
}
```
```
○ → c2go transpile 50.c
panic: invalid identity: 'U1 **' [recovered]
	panic: bad type: 'U1 **' [recovered]
	panic: bad type: '[]U1 **'

goroutine 1 [running]:
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc4202cef00, 0x7)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x5a9500, 0xc4202cef60)
	/home/konstantin/Program/go/src/runtime/panic.go:489 +0x2cf
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc4202cef02, 0x5)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x5a9500, 0xc4202cef40)
	/home/konstantin/Program/go/src/runtime/panic.go:489 +0x2cf
github.com/elliotchance/c2go/util.NewIdent(0xc4202cef02, 0x5, 0x5)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:241 +0x260
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc4202cef02, 0x5, 0xc4202cef02, 0x5)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:125 +0x847
github.com/elliotchance/c2go/util.typeToExpr(0xc4202cef02, 0x5, 0x0, 0x0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:45 +0x7b
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc4202cef00, 0x7, 0xc4202cef00, 0x7)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:80 +0x206
github.com/elliotchance/c2go/util.typeToExpr(0xc4202cef00, 0x7, 0x0, 0x0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:45 +0x7b
github.com/elliotchance/c2go/util.NewTypeIdent(0xc4202cef00, 0x7, 0xc4202e2420, 0xc4202cef00)
	/home/konstantin/go/src/github.com/elliotchance/c2go/util/goast.go:250 +0x35
github.com/elliotchance/c2go/transpiler.transpileVarDecl(0xc4200d6000, 0xc420118c60, 0xc4202775a8, 0xc4200d6000, 0x6b2860, 0xc420118c60, 0x1, 0xc4202cea90, 0xc4200fbd10)
	/home/konstantin/go/src/github.com/elliotchance/c2go/transpiler/declarations.go:450 +0xb32
github.com/elliotchance/c2go/transpiler.transpileToNode(0x6b2860, 0xc420118c60, 0xc4200d6000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/transpiler/transpiler.go:479 +0x1aa
github.com/elliotchance/c2go/transpiler.transpileTranslationUnitDecl(0xc4200d6000, 0xc4200c7ee0, 0xc420277738, 0xc4200d6000, 0x6b2620, 0xc4200c7ee0, 0x0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/transpiler/translation_unit.go:49 +0x6d7
github.com/elliotchance/c2go/transpiler.transpileToNode(0x6b2620, 0xc4200c7ee0, 0xc4200d6000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/transpiler/transpiler.go:462 +0x6d0
github.com/elliotchance/c2go/transpiler.TranspileAST(0x0, 0x0, 0x5e6a4d, 0x4, 0xc4200d6000, 0x6b2620, 0xc4200c7ee0, 0x0, 0x380)
	/home/konstantin/go/src/github.com/elliotchance/c2go/transpiler/transpiler.go:32 +0x212
main.Start(0x0, 0xc42000e3b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5e6a4d, ...)
	/home/konstantin/go/src/github.com/elliotchance/c2go/main.go:294 +0xc1e
main.runCommand(0xc4200001a0)
	/home/konstantin/go/src/github.com/elliotchance/c2go/main.go:419 +0x4f1
main.main()
	/home/konstantin/go/src/github.com/elliotchance/c2go/main.go:343 +0x22
```

**Comment by Konstantin8105** [comment]
Go code after #622:
```c
var g_82 U1 = U1{3}
var g_228 [][]U1 = (&[5][]U1{[]U1{U1{4294967292}, U1{4294967295}, U1{0}, U1{55266602}, U1{0}, U1{4294967295}}, []U1{U1{4294967295}, U1{4294967292}, U1{4294967292}, U1{4294967295}, U1{0}, U1{55266602}}})[:]
var g_506 []U1 = (*[1]U1)(unsafe.Pointer(&g_228[2][4]))[:]
var g_1246 []U1 = (*[1][]U1)(unsafe.Pointer(&g_506))[:]
var g_1245 []U1 ** = (*[1][]U1)(unsafe.Pointer(&g_1246))[:] // <- PROBLEM HERE
```
Problem: type `[]U1 **` is not Go type
