### ISSUE TITLE
Compile: triangle.c

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#560]
Transpilation: triangle.
Location of source: https://www.cs.cmu.edu/~quake/triangle.html
```cmd
○ → c2go transpile triangle.c
panic: invalid identity: 'insertvertexresult ()' [recovered]
	panic: bad type: 'insertvertexresult ()' [recovered]
	panic: bad type: '[1]insertvertexresult ()' [recovered]
	panic: bad type: '*[1]insertvertexresult ()' [recovered]
	panic: bad type: '(*[1]insertvertexresult ())'

goroutine 1 [running]:
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc422f00e40, 0x1b)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x632c00, 0xc4219003b0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc422f00e41, 0x19)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x632c00, 0xc421900390)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc422f00e42, 0x18)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x632c00, 0xc421900370)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc422f00e45, 0x15)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x632c00, 0xc421900350)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/elliotchance/c2go/util.NewIdent(0xc422f00e45, 0x15, 0x15)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:256 +0xac4
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc422f00e45, 0x15, 0xc422f00e45, 0x15)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:140 +0x83a
github.com/elliotchance/c2go/util.typeToExpr(0xc422f00e45, 0x15, 0x0, 0x0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:45 +0x7b
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc422f00e42, 0x18, 0xc422f00e42, 0x18)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:128 +0x6da
github.com/elliotchance/c2go/util.typeToExpr(0xc422f00e42, 0x18, 0x0, 0x0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:45 +0x7b
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc422f00e41, 0x19, 0xc422f00e41, 0x19)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:88 +0x8ca
github.com/elliotchance/c2go/util.typeToExpr(0xc422f00e41, 0x19, 0x0, 0x0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:45 +0x7b
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc422f00e40, 0x1b, 0xc422f00e40, 0x1b)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:81 +0x14d
github.com/elliotchance/c2go/util.typeToExpr(0xc422f00e40, 0x1b, 0x0, 0x0)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:45 +0x7b
github.com/elliotchance/c2go/util.NewCallExpr(0xc422f00e40, 0x1b, 0xc421900330, 0x1, 0x1, 0xc421eb5d40)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:151 +0x39
github.com/elliotchance/c2go/util.CreateSliceFromReference(0xc42285341c, 0x15, 0x7bfce0, 0xc4249e1820, 0x15)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:352 +0x21b
github.com/elliotchance/c2go/transpiler.transpileUnaryOperator(0xc420d35860, 0xc42040a1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/lepricon/go/src/github.com/elliotchance/c2go/transpiler/unary.go:430 +0x3ba
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x7c1f60, 0xc420d35860, 0xc42040a1e0, 0xc423ac1900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/lepricon/go/src/github.com/elliotchance/c2go/transpiler/transpiler.go:150 +0x1548
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x7c0ba0, 0xc42086ba70, 0xc42040a1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/lepricon/go/src/github.com/elliotchance/c2go/transpiler/transpiler.go:206 +0x1d1
```

**Comment by Konstantin8105** [comment]
Now, for present revisioin result is different and it is nice
```
/tmp/c2go-rating-c2go359450271/1.go:1830:6: __itimer_which_t redeclared in this block
	previous declaration at /tmp/c2go-rating-c2go359450271/1.go:1826:6
/tmp/c2go-rating-c2go359450271/1.go:3412:68: undefined: noarch.Float64SliceSliceSliceToUint32
/tmp/c2go-rating-c2go359450271/1.go:3413:27: undefined: noarch.Float64SliceSliceToUint32
/tmp/c2go-rating-c2go359450271/1.go:3414:19: undefined: noarch.Uint32ToFloat64SliceSliceSlice
/tmp/c2go-rating-c2go359450271/1.go:3414:58: undefined: noarch.Float64SliceSliceToUint32
/tmp/c2go-rating-c2go359450271/1.go:3415:18: invalid operation: printtri.tri == m[0].dummytri (slice can only be compared to nil)
/tmp/c2go-rating-c2go359450271/1.go:3418:53: undefined: noarch.Float64SliceSliceSliceToUint32
/tmp/c2go-rating-c2go359450271/1.go:3420:27: undefined: noarch.Float64SliceSliceToUint32
/tmp/c2go-rating-c2go359450271/1.go:3421:19: undefined: noarch.Uint32ToFloat64SliceSliceSlice
/tmp/c2go-rating-c2go359450271/1.go:3421:58: undefined: noarch.Float64SliceSliceToUint32
```

**Comment by Konstantin8105** [comment]
Now, panic:
```
 2018-02-10 10:18:19 ⌚  lepricon-AOD270 in ~/go/src/templorary/triangle
○ → c2go transpile triangle.c

panic: invalid identity: 'event **' [recovered]
	panic: bad type: 'event **' [recovered]
	panic: bad type: '[]event **'

goroutine 1 [running]:
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc423a14540, 0xa)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x644f00, 0xc422847360)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/elliotchance/c2go/util.typeToExpr.func1(0xc423a14542, 0x8)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:41 +0x115
panic(0x644f00, 0xc422847340)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/elliotchance/c2go/util.NewIdent(0xc423a14542, 0x8, 0x699440)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:259 +0xac4
github.com/elliotchance/c2go/util.internalTypeToExpr(0xc423a14542, 0x8, 0xc423a14542, 0x8)
	/home/lepricon/go/src/github.com/elliotchance/c2go/util/goast.go:166 +0x955
github.com/elliotchance/c2go/util.typeToExpr(0xc423a14542, 0x8, 0x0, 0x0)
```

**Comment by Konstantin8105** [comment]
```
 2018-02-28 22:17:08 ⌚  lepricon-AOD270 in ~/go/src/templorary/triangle
○ → c2go transpile triangle.c 

 2018-02-28 22:18:04 ⌚  lepricon-AOD270 in ~/go/src/templorary/triangle
○ → go run triangle.go 
# command-line-arguments
./triangle.go:2882:23: cannot use b[0].innodefilename (type [2048]byte) as type []byte in argument to noarch.Strncpy
./triangle.go:2889:98: cannot use b[0].innodefilename (type [2048]byte) as type []byte in argument to noarch.Strlen
```

**Comment by elliotchance** [comment]
@Konstantin8105 why did you close this issue?
