### ISSUE TITLE
Syslog integration test fails in docker container

### ISSUE THREAD

**Issue by kamphaus** [elliotchance/c2go#674]
When I run the integration tests in a docker container, I get the following:
```
--- FAIL: TestIntegrationScripts/tests/syslog.c (1.78s)
        main_test.go:215: Expected 
                Got: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
                        panic: runtime error: invalid memory address or nil pointer dereference
                [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5da8c9]
                
                goroutine 19 [running]:
                testing.tRunner.func1(0xc4200c00f0)
                        /usr/local/go/src/testing/testing.go:711 +0x5d9
                panic(0x6103e0, 0x74c950)
                        /usr/local/go/src/runtime/panic.go:491 +0x2a2
                log/syslog.(*Writer).writeAndRetry(0x0, 0x5, 0xc4200a40c0, 0x13, 0x0, 0x0, 0x0)
                        /usr/local/go/src/log/syslog/syslog.go:248 +0x69
                log/syslog.(*Writer).Notice(0x0, 0xc4200a40c0, 0x13, 0xc4200a40c0, 0xc4200c40c0)
                        /usr/local/go/src/log/syslog/syslog.go:229 +0x56
                github.com/elliotchance/c2go/noarch.internalSyslog(0x5, 0xc4200a40c0, 0x13)
                        github.com/elliotchance/c2go/noarch/_obj/syslog.go:72 +0x222
                github.com/elliotchance/c2go/noarch.Syslog(0x5, 0xc420049e40, 0xf, 0x20, 0xc420088200, 0x2, 0x2)
                        github.com/elliotchance/c2go/noarch/_obj/syslog.go:43 +0x19c
                command-line-arguments.main()
                        build/tests/syslog/main_test.go:343 +0x360
                command-line-arguments.TestApp(0xc4200c00f0)
                        build/tests/syslog/main_test.go:368 +0x11c
                testing.tRunner(0xc4200c00f0, 0x64a2a0)
                        /usr/local/go/src/testing/testing.go:746 +0x16d
                created by testing.(*T).Run
                        /usr/local/go/src/testing/testing.go:789 +0x569
                
                Parts of code:
                +========================+
                File : ./build/tests/syslog/main_test.go
```

**Comment by kamphaus** [comment]
The problem is that `noarch/syslog.go` uses the Go syslog client, which tries to connect to a unix socket on `/dev/log`, `/var/run/syslog` or `/var/run/log`. Those did not exist in my docker container.

What's strange is that if I run `clang -lm syslog.c -o a.out && ./a.out`, it works and I get the expected output (`1..0`).

A workaround is to use netcat (package `netcat-openbsd`) to mock the syslog socket: `nc -l -U /var/run/syslog &` (closes after one use).
