### ISSUE TITLE
panic: unknown operator: __extension__ for UnaryOperator __extension__ in AST

### ISSUE THREAD

**Issue by kph** [elliotchance/c2go#731]
The following C creates the following panic:

```
#define list_entry(ptr, type, member) __extension__ ({              \
	const typeof( ((type *)0)->member ) *__mptr = (ptr);   \
	(type *)( (char *)__mptr - offsetof(type,member) );})
```

In AST:

`| | |   |   `-UnaryOperator 0x2164298 <col:19, col:230> 'struct blkid_struct_dev *' prefix '__extension__'
`
```
panic: unknown operator: __extension__

goroutine 1 [running]:
github.com/elliotchance/c2go/transpiler.getTokenForOperator(0xc420672bd4, 0xd, 0xc4207341c8)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/operators.go:443 +0xc1a
github.com/elliotchance/c2go/transpiler.transpileUnaryOperator(0xc420517900, 0xc4200b66c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/unary.go:584 +0xd7
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x6b39a0, 0xc420517900, 0xc4200b66c0, 0x6b2400, 0x0, 0x0, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:168 +0xafd
github.com/elliotchance/c2go/transpiler.atomicOperation(0x6b39a0, 0xc420517900, 0xc4200b66c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/operators.go:473 +0xa5
github.com/elliotchance/c2go/transpiler.transpileBinaryOperator(0xc4201c5320, 0xc4200b66c0, 0xc420734a00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/binary.go:223 +0xc58
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x6b2420, 0xc4201c5320, 0xc4200b66c0, 0xc4200b6600, 0x0, 0x0, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:165 +0xe03
github.com/elliotchance/c2go/transpiler.transpileParenExpr(0xc4201c5290, 0xc4200b66c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/operators.go:160 +0xfd
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x6b33a0, 0xc4201c5290, 0xc4200b66c0, 0xc420734c00, 0x0, 0x0, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:183 +0xcb6
github.com/elliotchance/c2go/transpiler.atomicOperation(0x6b33a0, 0xc4201c5290, 0xc4200b66c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/operators.go:473 +0xa5
github.com/elliotchance/c2go/transpiler.transpileBinaryOperator(0xc4201c5200, 0xc4200b66c0, 0xc420735300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/binary.go:216 +0xadf
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x6b2420, 0xc4201c5200, 0xc4200b66c0, 0xc420672500, 0x0, 0x0, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:165 +0xe03
github.com/elliotchance/c2go/transpiler.atomicOperation(0x6b2420, 0xc4201c5200, 0xc4200b66c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/operators.go:473 +0xa5
github.com/elliotchance/c2go/transpiler.transpileBinaryOperator(0xc4201c50e0, 0xc4200b66c0, 0xc420735b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/binary.go:223 +0xc58
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x6b2420, 0xc4201c50e0, 0xc4200b66c0, 0xc420735b00, 0x0, 0x0, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:165 +0xe03
github.com/elliotchance/c2go/transpiler.transpileIfStmt(0xc4203b6ea0, 0xc4200b66c0, 0xc420735e00, 0xc420735e18, 0x6b2e60, 0xc4203b6ea0, 0x0, 0xc420000180, 0xc420898500, 0x6, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/branch.go:65 +0xe8
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b2e60, 0xc4203b6ea0, 0xc4200b66c0, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:337 +0xf70
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b2e60, 0xc4203b6ea0, 0xc4200b66c0, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileCompoundStmt(0xc42011c0e0, 0xc4200b66c0, 0xc420736050, 0xc420736068, 0x6b26a0, 0xc42011c0e0, 0x640340, 0xc420000180, 0xc42076e3c0, 0x7ef290, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:21 +0x10d
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b26a0, 0xc42011c0e0, 0xc4200b66c0, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:347 +0xc59
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b26a0, 0xc42011c0e0, 0xc4200b66c0, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileToBlockStmt(0x6b26a0, 0xc42011c0e0, 0xc4200b66c0, 0x6b2e00, 0xc4203b6e40, 0x67ca00, 0x0, 0x0, 0xc420193140, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:38 +0x43
github.com/elliotchance/c2go/transpiler.transpileIfStmt(0xc4203b6e40, 0xc4200b66c0, 0xc4207363f0, 0xc420736408, 0x6b2e60, 0xc4203b6e40, 0xc420024500, 0xc420000180, 0xc42076ea00, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/branch.go:85 +0x330
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b2e60, 0xc4203b6e40, 0xc4200b66c0, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:337 +0xf70
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b2e60, 0xc4203b6e40, 0xc4200b66c0, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileCompoundStmt(0xc420490380, 0xc4200b66c0, 0xc420736640, 0xc420736658, 0x6b26a0, 0xc420490380, 0x4, 0xc420000180, 0xc42076f3c0, 0x30, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:21 +0x10d
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b26a0, 0xc420490380, 0xc4200b66c0, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:347 +0xc59
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b26a0, 0xc420490380, 0xc4200b66c0, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileToBlockStmt(0x6b26a0, 0xc420490380, 0xc4200b66c0, 0x6b2b00, 0xc42050f7a0, 0x67ca00, 0x0, 0x0, 0xc4206ea340, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:38 +0x43
github.com/elliotchance/c2go/transpiler.transpileForStmt(0xc42050f7a0, 0xc4200b66c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/branch.go:349 +0xac1
github.com/elliotchance/c2go/transpiler.transpileWhileStmt(0xc42007ef60, 0xc4200b66c0, 0xc420736c18, 0xc420736c30, 0x6b3c20, 0xc42007ef60, 0xc420024500, 0xc420000180, 0xc42076fb80, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/branch.go:453 +0x225
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b3c20, 0xc42007ef60, 0xc4200b66c0, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:327 +0x114d
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b3c20, 0xc42007ef60, 0xc4200b66c0, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileCompoundStmt(0xc4200f1c70, 0xc4200b66c0, 0xc420736e68, 0xc420736e80, 0x6b26a0, 0xc4200f1c70, 0x7fcbc367f6c8, 0xc420000180, 0xc420286080, 0xc4208bbf00, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:21 +0x10d
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b26a0, 0xc4200f1c70, 0xc4200b66c0, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:347 +0xc59
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b26a0, 0xc4200f1c70, 0xc4200b66c0, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileToBlockStmt(0x6b26a0, 0xc4200f1c70, 0xc4200b66c0, 0xc420824400, 0x4, 0xc4208bbf40, 0x3, 0x4, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:38 +0x43
github.com/elliotchance/c2go/transpiler.transpileFunctionDecl(0xc420515790, 0xc4200b66c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/functions.go:86 +0x16de
github.com/elliotchance/c2go/transpiler.transpileToNode(0x6b2ce0, 0xc420515790, 0xc4200b66c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:443 +0x3f7
github.com/elliotchance/c2go/transpiler.transpileTranslationUnitDecl(0xc4200b66c0, 0xc420506040, 0xc420134000, 0x2d5, 0x400, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/translation_unit.go:116 +0x184
github.com/elliotchance/c2go/transpiler.transpileToNode(0x6b3820, 0xc420506040, 0xc4200b66c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:440 +0xaf1
github.com/elliotchance/c2go/transpiler.TranspileAST(0x0, 0x0, 0x67cc8d, 0x4, 0xc4200b66c0, 0x6b3820, 0xc420506040, 0x0, 0x5c000)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:32 +0x1f5
main.Start(0x1, 0xc420094090, 0x1, 0x1, 0xc4200e4240, 0x3, 0x4, 0x0, 0x0, 0x67cc8d, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/main.go:301 +0xf53
main.runCommand(0xc420080058)
	/home/kph/gopath/src/github.com/elliotchance/c2go/main.go:433 +0x484
main.main()
	/home/kph/gopath/src/github.com/elliotchance/c2go/main.go:356 +0x22

```

**Comment by kph** [comment]
I've tried a few ways to fix this, but I must not understand the structure of c2go well enough to do this yet. Mostly I have tried modifying transpileUnaryOperator() to ignore __extension__, but then I get panic: index out of range. I've hacked transpileStmtExpr() to have a bounds check, but this seems hacky.

Can you give me any pointers for writing tests for this, and fixing it? Happy to write the code, just need a little assistance.

Thanks,
Kevin

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/elliotchance/c2go/transpiler.transpileStmtExpr(0xc420270690, 0xc42027e120, 0xc420ec7c28, 0xc420ec7c40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/unary.go:686 +0x44d
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x6b3720, 0xc420270690, 0xc42027e120, 0x6b3900, 0x0, 0x0, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:207 +0x1696
github.com/elliotchance/c2go/transpiler.atomicOperation(0x6b39a0, 0xc4207303c0, 0xc42027e120, 0x0, 0x0, 0x0, 0x0, 0x7ef290, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/operators.go:545 +0xe93
github.com/elliotchance/c2go/transpiler.transpileBinaryOperator(0xc420833950, 0xc42027e120, 0xc420ec8301, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/binary.go:223 +0xc58
github.com/elliotchance/c2go/transpiler.transpileToExpr(0x6b2420, 0xc420833950, 0xc42027e120, 0xc420ec8401, 0x0, 0x0, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:165 +0xe03
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b2420, 0xc420833950, 0xc42027e120, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:387 +0x1ad
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b2420, 0xc420833950, 0xc42027e120, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileCompoundStmt(0xc420270380, 0xc42027e120, 0xc420ec86e8, 0xc420ec8700, 0x6b26a0, 0xc420270380, 0x5eb91d, 0xc420000180, 0xc42005c300, 0x43d987, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:21 +0x10d
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b26a0, 0xc420270380, 0xc42027e120, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:347 +0xc59
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b26a0, 0xc420270380, 0xc42027e120, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileToBlockStmt(0x6b26a0, 0xc420270380, 0xc42027e120, 0x6b2b00, 0xc4209d27e0, 0x67ca00, 0x0, 0x0, 0xc4200df350, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:38 +0x43
github.com/elliotchance/c2go/transpiler.transpileForStmt(0xc4209d27e0, 0xc42027e120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/branch.go:349 +0xac1
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b2be0, 0xc4209d27e0, 0xc42027e120, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:341 +0x6f7
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b2be0, 0xc4209d27e0, 0xc42027e120, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileCompoundStmt(0xc4203d5500, 0xc42027e120, 0xc420ec8e68, 0xc420ec8e80, 0x6b26a0, 0xc4203d5500, 0x7fc87ed966c8, 0xc420000180, 0xc4202aa000, 0x4315bb, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:21 +0x10d
github.com/elliotchance/c2go/transpiler.transpileToStmt(0x6b26a0, 0xc4203d5500, 0xc42027e120, 0x0, 0x0, 0x7ef290, 0x0, 0x0, 0x7ef290, 0x0, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:347 +0xc59
github.com/elliotchance/c2go/transpiler.transpileToStmts(0x6b26a0, 0xc4203d5500, 0xc42027e120, 0x7ef290, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:265 +0xe5
github.com/elliotchance/c2go/transpiler.transpileToBlockStmt(0x6b26a0, 0xc4203d5500, 0xc42027e120, 0xc42095b280, 0xc420ec8fe0, 0x4b4281, 0xc4206e4100, 0xc4210b1700, 0x1b, 0xc4210b1700, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/scope.go:38 +0x43
github.com/elliotchance/c2go/transpiler.transpileFunctionDecl(0xc420d61c70, 0xc42027e120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/functions.go:86 +0x16de
github.com/elliotchance/c2go/transpiler.transpileToNode(0x6b2ce0, 0xc420d61c70, 0xc42027e120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:443 +0x3f7
github.com/elliotchance/c2go/transpiler.transpileTranslationUnitDecl(0xc42027e120, 0xc4205fa040, 0xc420988000, 0x309, 0x400, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/translation_unit.go:116 +0x184
github.com/elliotchance/c2go/transpiler.transpileToNode(0x6b3820, 0xc4205fa040, 0xc42027e120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:440 +0xaf1
github.com/elliotchance/c2go/transpiler.TranspileAST(0x0, 0x0, 0x67cc8d, 0x4, 0xc42027e120, 0x6b3820, 0xc4205fa040, 0x0, 0x66000)
	/home/kph/gopath/src/github.com/elliotchance/c2go/transpiler/transpiler.go:32 +0x1f5
main.Start(0x1, 0xc42000e130, 0x1, 0x1, 0xc42005c280, 0x3, 0x4, 0x0, 0x0, 0x67cc8d, ...)
	/home/kph/gopath/src/github.com/elliotchance/c2go/main.go:301 +0xf53
main.runCommand(0xc42001a0b8)
	/home/kph/gopath/src/github.com/elliotchance/c2go/main.go:433 +0x484
main.main()
	/home/kph/gopath/src/github.com/elliotchance/c2go/main.go:356 +0x22

```

**Comment by elliotchance** [comment]
This is a tricky one because I'm not sure what the AST node is supposed to mean...

I can't play with the code right now but what I suggest you do is put the code into a test and do whatever it takes to get it functionality working first.

Your initial thought of modifying transpileUnaryOperator() is probably going to be correct, although I suspect that you will need to return some dummy data back to prevent the next stage from panicking. You will only be able to experiment with this dummy value after the code is working in a test (that may hint to how it's supposed to behave).

Let me know how you go 😄
