### ISSUE TITLE
unknown node type: "avx512vl"

### ISSUE THREAD

**Issue by lieff** [elliotchance/c2go#750]
I'm trying to translate https://github.com/lieff/minimp3/blob/master/minimp3_test.c
but getting this error:
```
c2go transpile minimp3_test.c
panic: unknown node type: 'TargetAttr 0x563c6f4606a8 <line:579:74, col:95> "avx512vl"'

goroutine 65 [running]:
github.com/elliotchance/c2go/ast.Parse(0xc424fa0f96, 0x3a, 0x68b37a, 0x5)
        /home/lion/.go/src/github.com/elliotchance/c2go/ast/ast.go:264 +0x424f
main.convertLinesToNodes(0xc420a8bc60, 0x2538, 0x129c7, 0x6c2f302e362d6d76, 0x676e616c632f6269, 0x692f302e302e362f)
        /home/lion/.go/src/github.com/elliotchance/c2go/main.go:89 +0x198
main.convertLinesToNodesParallel.func1.1(0xc420468000, 0xc42000c008, 0xc420a8bc60, 0x2538, 0x129c7, 0x0)
        /home/lion/.go/src/github.com/elliotchance/c2go/main.go:113 +0x59
created by main.convertLinesToNodesParallel.func1
        /home/lion/.go/src/github.com/elliotchance/c2go/main.go:111 +0x112

```
Hmm, avx? But code uses only sse intrinsic, clang execution problem?
Here ast output:
[ast.txt](https://github.com/elliotchance/c2go/files/2108548/ast.txt)

**Comment by elliotchance** [comment]
c2go works by parsing the AST tree output from clang. This is one case where c2go does not know how to deal with the `TargetAttr` type of node.

This is very easily fixed by creating the node type and a unit test. Here is a recent PR that does exactly that: https://github.com/elliotchance/c2go/pull/770

Let me know if you run into any troubles :)

**Comment by lieff** [comment]
Thanks for reply :)
Ah, I see
```
|-FunctionDecl 0x5589fa46f218 <line:44:1, line:48:1> line:45:1 _mm_empty 'void (void)' static inline
| |-CompoundStmt 0x5589fa46f468 <line:46:1, line:48:1>
| | `-CallExpr 0x5589fa46f410 <line:47:5, col:25> 'void'
| |   `-ImplicitCastExpr 0x5589fa46f3f8 <col:5> 'void (*)(void)' <BuiltinFnToFnPtr>
| |     `-DeclRefExpr 0x5589fa46f3d0 <col:5> '<builtin fn type>' Function 0x5589fa46f330 '__builtin_ia32_emms' 'void (void)'
| |-TargetAttr 0x5589fa46f2b8 <line:44:71, col:87> "mmx"
| |-NoDebugAttr 0x5589fa46f310 <col:58>
| |-AlwaysInlineAttr 0x5589fa46f320 <col:39> always_inline
```
This is some kind of function metadata, what instruction sets used. Most of functions marked "mmx", "sse", "f16c", "sse2", "sse3", "ssse3", "sse4.1", "aes", "clflushopt", "clwb", "avx", "avx2", "bmi", "bmi2", "lzcnt", "fma",  "avx512f" and "avx512vl" triggers the error.
So, we must just skip this node? Or may be just change clang invocation to disable avx* instruction set?
