### ISSUE TITLE
Error: preprocess for file: [prime.c] failed: exec: "clang": executable file not found in %PATH% StdErr =

### ISSUE THREAD

**Issue by Huwaiza** [elliotchance/c2go#824]

**Comment by elliotchance** [comment]
You will need to have [clang installed](https://clang.llvm.org. Clang is a C compiler and does the parsing of the source files and produces an AST that can be understood by c2go.

**Comment by Huwaiza** [comment]
Installed it but still was showing errors even on the programs you gave as
an example

**Comment by elliotchance** [comment]
Please include the errors in the issue.

**Comment by Huwaiza** [comment]
*It's fib.c *
*panic: could not match regexp with string*
*^(?P<address>[0-9a-fx]+) <(?P<position>.*)>
'(?P<type>.*?)'(:'(?P<type2>.*)')?(?P<lvalue> lvalue)?(?P<prefix>
prefix)?(?P<postfix> postfix)? '(?P<operator>.*?)'[\s]*$*
*0x1c586fd7950 <col:14, col:44> 'unsigned long long' lvalue prefix '*'
cannot overflow*


*goroutine 52 [running]:*
*github.com/elliotchance/c2go/ast.groupsFromRegex(0xc0000346e0
<http://github.com/elliotchance/c2go/ast.groupsFromRegex(0xc0000346e0>,
0xa6, 0xc0005733bc, 0x55, 0x3d)*
*        C:/Users/huwai/OneDrive/Documents/GitHub/c2go/ast/ast.go:286
+0x364*
*github.com/elliotchance/c2go/ast.parseUnaryOperator(0xc0005733bc
<http://github.com/elliotchance/c2go/ast.parseUnaryOperator(0xc0005733bc>,
0x55, 0x6c9de1)*
*
C:/Users/huwai/OneDrive/Documents/GitHub/c2go/ast/unary_operator.go:16
+0x69*
*github.com/elliotchance/c2go/ast.Parse(0xc0005733ae
<http://github.com/elliotchance/c2go/ast.Parse(0xc0005733ae>, 0x63,
0x6c564d, 0x5)*
*        C:/Users/huwai/OneDrive/Documents/GitHub/c2go/ast/ast.go:246
+0x21e5*
*main.convertLinesToNodes(0xc0000d8260, 0x627, 0x1275, 0x20646574726f7070,
0x6320656874207962, 0x6320746e65727275)*
*        C:/Users/huwai/OneDrive/Documents/GitHub/c2go/main.go:89 +0x1cf*
*main.convertLinesToNodesParallel.func1.2(0xc0003260c0, 0xc00031e000,
0xc0000d8260, 0x627, 0x1275, 0x0)*
*        C:/Users/huwai/OneDrive/Documents/GitHub/c2go/main.go:121 +0x5a*
*created by main.convertLinesToNodesParallel.func1*
*        C:/Users/huwai/OneDrive/Documents/GitHub/c2go/main.go:119 +0x1ad*

**Comment by elliotchance** [comment]
That error is caused by c2go not being able to understand the output from clang.

Unfortunately, you are seeing this because no windows distributions are part of the CI pipeline. They are less thoroughly tested than the Linux version.

You can have a go at fixing this by covering the case by following this example: https://github.com/elliotchance/c2go/pull/760/files

**Comment by Konstantin8105** [comment]
Please try https://github.com/Konstantin8105/c4go

**Comment by Huwaiza** [comment]
Thanks but i have already done it manually

**Comment by AvinashRamashray** [comment]
@Huwaiza

Please post the fix here for this issue...
I am also getting exactly same issue....
