### ISSUE TITLE
panic when including stddef.h; unknown node type: 'ConstantExpr'

### ISSUE THREAD

**Issue by mewmew** [elliotchance/c2go#829]
Hi @elliotchance,

I know you've taken a pause from the project. So just wanted to say that I very much appreciate the time you've put in thus far! It's quite impressive what `c2go` is already capable of.

Consider this an issue for "the future", if you ever feel like getting back into coding on the project, or if someone else picks up the torch.

The following example code generates a panic when running `c2go transpile a.c`:

Contents of `a.c`:

```c
#include <stddef.h>

int f() {
	return 42;
}
```

(The important line is the `stddef.h`, I just included the function `f` to have some output to verify that "something happened" during the transpilation).

And the corresponding panic is as follows (on rev 4de3ec97b368135e371d3b0667f6345a9267f43c):

```
panic: unknown node type: 'ConstantExpr 0x562cf36b7190 <col:34, col:55> 'unsigned long''

goroutine 26 [running]:
github.com/elliotchance/c2go/ast.Parse(0xc00018e6b7, 0x3c, 0x6afb99, 0x5)
	/home/u/goget/src/github.com/elliotchance/c2go/ast/ast.go:272 +0x32e7
main.convertLinesToNodes(0xc0000d6630, 0xa, 0x14, 0x0, 0x0, 0x0)
	/home/u/goget/src/github.com/elliotchance/c2go/main.go:89 +0x1a6
main.convertLinesToNodesParallel.func1.1(0xc0000a2240, 0xc000096168, 0xc0000d6630, 0xa, 0x14, 0x0)
	/home/u/goget/src/github.com/elliotchance/c2go/main.go:113 +0x53
created by main.convertLinesToNodesParallel.func1
	/home/u/goget/src/github.com/elliotchance/c2go/main.go:111 +0x12a
```

This is on Clang 9.0:

```
u@x220 ~> clang -v
clang version 9.0.1 
Target: x86_64-pc-linux-gnu
```

The header file `stddef.h` (included from `a.c`) includes `__stddef_max_align_t.h` (which is part of Clang), the contents of which is as follows:

```c
/*===---- __stddef_max_align_t.h - Definition of max_align_t for modules ---===
 *
 * Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
 * See https://llvm.org/LICENSE.txt for license information.
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 *
 *===-----------------------------------------------------------------------===
 */

#ifndef __CLANG_MAX_ALIGN_T_DEFINED
#define __CLANG_MAX_ALIGN_T_DEFINED

#if defined(_MSC_VER)
typedef double max_align_t;
#elif defined(__APPLE__)
typedef long double max_align_t;
#else
// Define 'max_align_t' to match the GCC definition.
typedef struct {
  long long __clang_max_align_nonce1
      __attribute__((__aligned__(__alignof__(long long))));
  long double __clang_max_align_nonce2
      __attribute__((__aligned__(__alignof__(long double))));
} max_align_t;
#endif

#endif
```

Wish you all the best and a happy spring to come!

Cheers,
Robin

**Comment by mewmew** [comment]
This issue is resolved with PR #830.

For reference, this is what the `c2go` output now looks like for `a.c` above.

```go
/*
	Package main - transpiled by c2go version: v0.25.9 Dubnium 2018-12-30

	If you have found any issues, please raise an issue at:
	https://github.com/elliotchance/c2go/
*/

package main

type ptrdiff_t int32
type size_t uint32
type wchar_t int32
type max_align_t struct {
	__clang_max_align_nonce1 int64
	__clang_max_align_nonce2 float64
}

// f - transpiled function from  /home/u/Desktop/ccc/a/a.c:3
func f() int32 {
	return int32(42)
}
func init() {
}
```
