### ISSUE TITLE
panic: unknown node type: 'BuiltinAttr 0x10db7b0 <<invalid sloc>> Inherited Implicit 749'

### ISSUE THREAD

**Issue by MSGermany** [elliotchance/c2go#891]
Hey, I have this problem:

`panic: unknown node type: 'BuiltinAttr 0x10db7b0 <<invalid sloc>> Inherited Implicit 749'

goroutine 13 [running]:
github.com/elliotchance/c2go/ast.Parse({0xc0002c6549, 0x3d})
	/home/smayer/go/pkg/mod/github.com/elliotchance/c2go@v0.26.10/ast/ast.go:294 +0x22d4
main.convertLinesToNodes({0xc0002ce5f0, 0x1c, 0x0?})
	/home/smayer/go/pkg/mod/github.com/elliotchance/c2go@v0.26.10/main.go:89 +0x115
main.convertLinesToNodesParallel.func1.1({0xc0002ce5f0?, 0x0?, 0x0?}, 0x0?)
	/home/smayer/go/pkg/mod/github.com/elliotchance/c2go@v0.26.10/main.go:113 +0x39
created by main.convertLinesToNodesParallel.func1
	/home/smayer/go/pkg/mod/github.com/elliotchance/c2go@v0.26.10/main.go:111 +0x1a5`

Can you help me with that ? I just can't get any further here.

Best regards

**Comment by rxa1031** [comment]
Hi,
Is there any solution for this or similar panic?
What does it mean?
What does the number after Implicit mean. What will the value 996 mean?
Regards,
Rajeev
